# Document:
# http://simiki.org/docs/configuration.html

url: http://XuXueHua.com
title: Xu XueHua
keywords: Xu XueHua
description: Xu XueHua's public notes
author: Xu XueHua

root: /
source: content
destination: output
themes_dir: themes
theme: simple2

category:
  - name: Linux  # 目录名
    label: Linux 运维  # 目录的别名, 生成首页时可以使用

default_ext: md
pygments: true
debug: false
